extends Area2D

##Will be set to false if being auto generated by level editor
@export var inEditor = true

@export_category("In Editor")

enum direction{Up, Right, Down, Left}
enum col{Purple, Blue, Red, Yellow}

@export var startDirection: direction
@export var endDirection: direction

@export var speed = 1.0

@export var length = 1

@export var inverted = false

##Up, Right, Down, Left, Wait
@export_range(0,4,1) var instructions: Array[int]

@export_category("Auto")

@export var type: int
@export var pos: Vector2i
@export var color: col

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass
